### ISSUE TITLE
Record timelapse

### ISSUE THREAD

**Issue by akuskis** [dalerank/Akhenaten#105]
@dalerank suggested to create timelapse videos (periodically make snapshots and create videos from it).

It should be configurable to take screenshots 1 - 24 times per day and frame rate should also be configurable.

**Comment by dalerank** [comment]
Cool

**Comment by dalerank** [comment]
Full city screenshot now work
I tryied to make it render in som threads, it works but need polish current solution
You may to use current logic for start
screenshot.cpp : full_city_screenshot

**Comment by dalerank** [comment]
game now can save video
