### ISSUE TITLE
No background in Top Menu

### ISSUE THREAD

**Issue by akuskis** [dalerank/Akhenaten#119]
![image](https://github.com/dalerank/Ozymandias/assets/3109998/24a48be1-4a30-4f08-9c89-a5a49a87e492)
But everything else - works (also sound)
![image](https://github.com/dalerank/Ozymandias/assets/3109998/8a1e5757-f117-4401-903a-72ceeedaf300)

**Comment by dalerank** [comment]
@akuskis check pls in latest changes

**Comment by akuskis** [comment]
Nope, the same issue.

A bit busy now... can take a look later.

https://github.com/dalerank/Ozymandias/assets/3109998/3b14382b-591d-4ffa-b73e-7a09c9e1cb13

**Comment by dalerank** [comment]
Got it, possible draw_background failed :(

**Comment by dalerank** [comment]
cnr last builds
