### ISSUE TITLE
Can't place village palace

### ISSUE THREAD

**Issue by jocke42** [dalerank/Akhenaten#137]
(Current git commit, played on Fedora-Linux)
Structure is not placeable, does not appear (should be visible at the "300" in the picture)
![image](https://github.com/dalerank/Akhenaten/assets/139220629/98fa5505-5e95-4260-915e-32b9d8e061ca)

**Comment by dalerank** [comment]
![image](https://github.com/dalerank/Akhenaten/assets/918081/8103d6e3-3e88-4647-b2cf-a2eefe3678ef)
