### ISSUE TITLE
Ostriches: Wrong objects and don't respawn

### ISSUE THREAD

**Issue by jocke42** [dalerank/Akhenaten#142]
(Current git commit, played on Fedora-Linux)
Instead of ostriches there are pyramid workers to hunt. For testing I hunted them down, got meat but the ostriches/workers didn't even respawn.
![image](https://github.com/dalerank/Akhenaten/assets/139220629/c66a42d8-2266-4be6-b98e-b9f542e7d6d3)

**Comment by dalerank** [comment]
fixed last week, pls check
