### ISSUE TITLE
Search for file case-insensitive

### ISSUE THREAD

**Issue by tintou** [dalerank/Akhenaten#144]
I'm using Linux and here the filesystem is case-sensitive, so doing `fopen(Pharaoh_MM.eng)` won't work if the file is named `Pharaoh_mm.eng` (which is the case here). There are several resources that are also missing because of this issue. It would be nice to implement a case-insensitive loading of resources.

**Comment by dalerank** [comment]
Thanks, nice idea

**Comment by dalerank** [comment]
@tintou can you create fix for this? I have no Linux,  and some fixes hard to implement

**Comment by dalerank** [comment]
@tintou I saw you prepared flatpack commit for augustus, could you please do the same here?

**Comment by tintou** [comment]
I just tested and it loading the files fine, thank you!
