### ISSUE TITLE
Can't open/load new game on macOS

### ISSUE THREAD

**Issue by jlsmith-hep** [dalerank/Akhenaten#152]
Bug: After building and running, I can create a family/save, but game crashes when I attempt to begin the game

OS/Machine: macOS 14.5, MacBook Pro M2 Pro

Build: from eae08e3, on macOS using VS Code, CMake, clang++ 15.0.0, c++17, using external SDL2 libraries from brew. SDL2: 2.30.4, SDL2 Mixer: 2.8.0

Crash: 
<img width="944" alt="Screenshot 2024-06-27 at 10 11 30" src="https://github.com/dalerank/Akhenaten/assets/59732519/d9a4dfe3-ba6b-4c63-847e-7a4e42d27067">

**Comment by dalerank** [comment]
Thanks, look asap

**Comment by jlsmith-hep** [comment]
Hi, as of the latest commit (89ecd53ad0ca79ceeea462f33a88498b915432f5) this bug still exists. I can now get to the scenario page, but the bug happens when I click "to the city". 

<img width="1512" alt="image" src="https://github.com/dalerank/Akhenaten/assets/59732519/7c551448-68f0-4ac8-b557-bca2bc79f088">
<img width="1512" alt="image" src="https://github.com/dalerank/Akhenaten/assets/59732519/5b5a6284-9073-42d5-b3e7-278f92c3ddfb">

**Comment by dalerank** [comment]
Git it, let me think what happens.
Can you show log here?

**Comment by jlsmith-hep** [comment]
[log.txt](https://github.com/user-attachments/files/16039712/log.txt)

Thanks! My background is more in data science and AI using C++ so unfortunately I don't know where to start with this error, but in general I am willing to help debug errors and contribute to this project

**Comment by dalerank** [comment]
All figures registered with one scheme 
`
ANK_REGISTER_CONFIG_ITERATOR(config_load_figure_immigrant);
`
an s->func it a list of simple structures
  s->next
    s->next->next
      s->next->next etc
so it need to understand why this scheme not works on mac
cause it works on win, linux and android

**Comment by dalerank** [comment]
Or I will get macbook on next week and try to debug it local

**Comment by jlsmith-hep** [comment]
I'll see if I can find some time to look at it , maybe in a week for me. It could be many things, this is also ARM rather than x86.
