### ISSUE TITLE
Crash when launch with datafiles from GOG version

### ISSUE THREAD

**Issue by drelbszoomer** [dalerank/Akhenaten#154]
Running the flatpak on Linux, pointing the data dir on startup to the  Pharaoh Gold data folder crashes with the attached logfile.
[akhenaten-log.txt](https://github.com/user-attachments/files/16734958/akhenaten-log.txt)

**Comment by dalerank** [comment]
Thanks, will fix soon. Tokenum.h incorrect work on linux

**Comment by dalerank** [comment]
fix in fd1c0ec416d1f8a19f9cc466328fbb4dabff44e3

**Comment by dalerank** [comment]
@drelbszoomer check pls all fixed
