### ISSUE TITLE
Documentation Recommendation

### ISSUE THREAD

**Issue by whipowill** [dalerank/Akhenaten#156]
You might add to the homepage some documentation about command line arguments.  For example, in order to get the scale I wanted I had to run the game line this:

```
exec Akhenaten.exe --display-scale 2 --cursor-scale 2 --render opengl --size 1920x1080 ../path/to/pharaoh
```

I had to look into your code to find out how to do this.

**Comment by dalerank** [comment]
Fixed in 6d3bf3e024ade42046f2abfc43b64eb9ccb53d79
